export enum Penalties {
    ABUSE = 'Abuse',
    BOARD = 'Board',
    CHARG = 'Charging',
    CROSS = 'Cross Check',
    DELAY = 'Delay of Game',
    ELBOW = 'Elbow',
    FIGHT = 'Fight',
    HOLD = 'Holding',
    HOOK = 'Hooking',
    INTRF = 'Interference',
    KICK = 'Kick',
    KNEE = 'Knee',
    MATCH = 'Match',
    ROUGH = 'Roughing',
    SLASH = 'Slashing',
    SPEAR = 'Spearing',
    TOOM = 'Too Many Men',
    TRIP = 'Tripping',
    UNSP = 'Un-Sportsman like',
}
