name: Build Nextjs App

on:
    pull_request:
        types: [opened, synchronize]
        branches:
            - '**'
        paths:
            - '**'
jobs:
    Next-App-Build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: '20.x'
                  cache: 'npm'
                  cache-dependency-path: ./stattracker/package-lock.json
            - run: npm ci
            - run: npm run build --if-present
